"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.Text = void 0;
var Text;
(function (Text) {
    Text["Clear"] = "Clear";
    Text["Cloudy"] = "Cloudy";
    Text["LightRainShower"] = "Light rain shower";
    Text["Overcast"] = "Overcast";
    Text["PartlyCloudy"] = "Partly cloudy";
    Text["PatchyLightDrizzle"] = "Patchy light drizzle";
    Text["PatchyRainPossible"] = "Patchy rain possible";
    Text["Sunny"] = "Sunny";
})(Text || (exports.Text = Text = {}));
